export const FETCH_EPISODE_PAGE_REQUEST = 'FETCH_EPISODE_PAGE_REQUEST';
export const FETCH_EPISODE_PAGE_FAILURE = 'FETCH_EPISODE_PAGE_FAILURE';
export const FETCH_EPISODE_PAGE_SUCCESS = 'FETCH_EPISODE_PAGE_SUCCESS';
