export const FETCH_GENRE_PAGE_REQUEST = 'FETCH_GENRE_PAGE_REQUEST';
export const FETCH_GENRE_PAGE_FAILURE = 'FETCH_GENRE_PAGE_FAILURE';
export const FETCH_GENRE_PAGE_SUCCESS = 'FETCH_GENRE_PAGE_SUCCESS';
